server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seconder_db
    username: postgres
    password: 12ShiZZiC97
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate